"use client";
import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./utils/ThemeProvider";
import ReduxProvider from "./Provider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap",
});

const roboto = Roboto({
	weight: ["100", "500", "400", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--forn-Roboto",
});

const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
	variable: "--forn-Poppins",
	display: "swap",
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				suppressHydrationWarning={true}
				className={`${inter.variable} ${poppins.variable}  bg-no-repeat `}
			>
				<ReduxProvider>
					<SessionProvider>
						<ThemeProvider
							attribute='class'
							defaultTheme='system'
							enableSystem
							disableTransitionOnChange
						>
							<ToastContainer />
							{children}
						</ThemeProvider>
					</SessionProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
